title: Elements of Scientific Computing
email: marcc-help@marcc.jhu.edu
description: >-
baseurl: "/esc"
url: "https://marcc-hpc.github.io"
# twitter_username: jekyllrb
github_username:  marcc-hpc
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
collections:
  notebooks:
    output: true
  articles:
    output: true
  common:
    output: true
parent_repository: http://github.com/marcc-hpc/esc
